shop/shop/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path(
        'add/<int:product>/',
        views.AddProductToCartView.as_view(),
        name="add-product-to-cart"),
    path(
        'view/',
        views.CartView.as_view(),
        name="view"),
    path(
        'delete/<int:pk>',
        views.DeleteItemDeleteView.as_view(),
        name="delete"),
]

shop/shop/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path(
        'check-out',
        views.OrderCheckoutView.as_view(),
        name="check-out"),
    path(
        'success/<int:pk>/',
        views.OrderCheckoutSuccess.as_view(),
        name="success"),
    # path(
    #     'list/',
    #     views.OrdersList.as_view(),
    #     name="list")
    path(
        'list-admin/',
        views.OrdersListAdmin.as_view(),
        name="list-admin")
]

shop/shop/theblog/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('index.urls')),
    path('admin_panel/', include('admin_panel.urls')),
    path('admin/', admin.site.urls),
    path('admin_panel/reference/',include('reference.urls')),
    path('admin_panel/products/',include('products.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/shop/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Book

User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name="Покупатель",
        blank=True,
        null=True,
        on_delete=models.CASCADE)
    created_date = models.DateTimeField(
        "Дата создания",
        auto_now=False,
        auto_now_add=True)
    updated_date = models.DateTimeField(
        "Дата изменения",
        auto_now=True,
        auto_now_add=False)

    def __str__(self):
        return "Корзина {}, покупателя {}".format(
            self.pk,
            self.user)

    @property
    def products_in_cart_count(self):
        total = 0
        for product in self.products_in_cart.all():
            total += product.quantity
        return total

    @property
    def total_price(self):
        total = 0
        for product in self.products_in_cart.all():
            total += product.price_total
        return total

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"


class ProductsInCart(models.Model):
    cart = models.ForeignKey(
        Cart,
        verbose_name="Продукт в корзине",
        related_name="products_in_cart",
        on_delete=models.CASCADE)
    product = models.ForeignKey(
        Book,
        on_delete=models.CASCADE)
    quantity = models.IntegerField(
        "Количество")
    created_date = models.DateTimeField(
        "Дата создания",
        auto_now=False,
        auto_now_add=True)
    updated_date = models.DateTimeField(
        "Дата изменения",
        auto_now=True,
        auto_now_add=False)

    def __str__(self):
        return "Товар {name}, кол-во {quantity} в корзине".format(
            name=self.product.name,
            quantity=self.quantity)

    @property
    def price(self):
        return self.product.price

    @property
    def price_total(self):
        return self.product.price * self.quantity


    class Meta:
        verbose_name = "Товар в корзине"
        verbose_name_plural = "Товары в корзине"
        unique_together = (
            ('cart', 'product')
        )

shop/shop/cart/forms.py
from django import forms

from .models import ProductsInCart


class AddProductForm(forms.ModelForm):
    class Meta:
        model = ProductsInCart

        fields = [
            'product',
            'quantity'
        ]
        widgets = {
            'product': forms.HiddenInput(),
        }

shop/shop/cart/views.py
from django.views.generic import UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy

from products.models import Book
from .models import ProductsInCart, Cart
from .forms import AddProductForm
from orders.forms import CheckoutOrderForm
from reference.models import OrderStatus


new_order_status = OrderStatus.objects.get(pk=1)

class AddProductToCartView(UpdateView):
    model = ProductsInCart
    template_name = 'cart/add-product.html'
    form_class = AddProductForm

    def get_success_url(self):
        print(self.request.POST.get('next', '/'), 'next')
        return self.request.POST.get('next', '/')

    def get_object(self):
        """
        Ек
        """
        cart_id = self.request.session.get('cart_id')
        product_id = self.kwargs.get('product')
        cart, cart_created = Cart.objects.get_or_create(
            pk=cart_id,
            defaults={
                'user': self.request.user
            }
        )
        product = Book.objects.get(pk=product_id)
        product_in_cart, created = ProductsInCart.objects.get_or_create(
            cart=cart,
            product=product,
            defaults={
                'cart': cart,
                'product': product,
                'quantity': 1},
        )
        if cart_created:
            self.request.session['cart_id'] = cart.pk
        elif not created:
            product_in_cart.quantity += 1
        return product_in_cart

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next"] = self.request.GET.get('next', '/')
        return context


class CartView(DetailView):
    model = Cart
    template_name = 'cart/view-cart.html'

    def get_object(self):
        cart_id = self.request.session.get('cart_id')
        cart, cart_created = Cart.objects.get_or_create(
            pk=cart_id,
            defaults={
                'user': self.request.user
            }
        )
        return cart

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        checkot_form = CheckoutOrderForm()
        checkot_form.fields['cart'].initial = self.object
        checkot_form.fields['status'].initial = new_order_status
        context["form"] = checkot_form
        return context


class DeleteItemDeleteView(DeleteView):
    model = ProductsInCart
    template_name = 'cart/delete-item.html'

    def get_success_url(self):
        return self.request.POST.get('next', '/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next"] = self.request.GET.get('next', '/')
        return context

shop/shop/cart/templates/cart/add-product.html
{% extends 'user_base.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="container">


<h1>{{ object.product.name }}</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="hidden" name="next" value="{{next}}">
    <button type="submit" class="btn btn-success btn-block">Добавить в корзину</button>
</form>
</div>
{% endblock body %}

shop/shop/cart/templates/cart/delete-item.html
{% extends 'user_base.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="container">


<h1>{{ object.product.name }}</h1>
<h2>{{ object.quantity }} шт</h2>

<form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{next}}">
    <button type="submit" class="btn btn-success btn-block">Удалить?</button>
</form>
</div>
{% endblock body %}

shop/shop/cart/templates/cart/view-cart.html
{% extends 'user_base.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="container">
<h1>Корзина</h1>
    <table class="table table-striped">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Книга</th>
        <th scope="col">Кол-во</th>
        <th scope="col">Цена за шт.</th>
        <th scope="col">Цена всего</th>
        <th scope="col">..</th>
        </tr>
    </thead>
    <tbody>
{% for product in object.products_in_cart.all %}
        <tr>
        <th scope="row">{{ product.pk }}</th>
        <td>{{ product.product.name }}</td>
        <td>{{ product.quantity }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.price_total }}</td>
        <td>
            <a href="{% url 'cart:delete' product.pk %}?next=/cart/view/" class="btn btn-danger btn-small"><i class="fas fa-trash"></i></a>
            <a href="{% url 'cart:add-product-to-cart' product.product.pk %}?next=/cart/view/" class="btn btn-success btn-small"><i class="fas fa-edit"></i></a>
        </td>
        </tr>
{% endfor %}
        <tr>
            <th scope="row" colspan="2">Итого:</th>
            <th scope="row" colspan="2">{{ object.products_in_cart_count }} шт.</th>
            <th scope="row" colspan="2">{{ object.total_price }} BYN</th>
        </tr>
    </tbody>
    </table>
    {% if object.products_in_cart_count > 0 %}
        <div class="card bg-light border-primary mb-3">
            <h5 class="card-header border-primary">Оформить заказ</h5>
                <form action="{% url 'orders:check-out' %}" method="POST" class="card-body">
                    {% csrf_token %}
                    <h5 class="card-title">* - обязательны для заполнения</h5>
                    <p class="card-text">{{ form|crispy }}</p>
                    <button class="btn btn-danger btn-block" type="submit">Оформить заказ</button>
                </form>
        </div>
    {% endif %}
{% endblock body %}